version: '3.9'

services:
  transit-mysql:
    build:
      context: ./mysql
    container_name: transit-mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - 3307:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - transit

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
    ports:
      - 8761:8761
    networks:
      - transit

  cloud-gateway:
    build:
      context: ./cloud-gateway
    container_name: cloud-gateway
    depends_on:
      - transit-mysql
      - eureka-server
    restart: always
    ports:
      - 8070:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=transit-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
      - SERVER_PORT=8080
      - REGISTRY_HOST=discovery
      - APP_NAME=gateway-service
    networks:
      - transit

  notifications-service:
    build:
      context: ./notifications-service
    #    container_name: transit-catalog
    depends_on:
      - transit-mysql
      - eureka-server
    restart: always
    #    ports:
    #      - 8080:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=transit-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
      - SERVER_PORT=8080
      - REGISTRY_HOST=discovery
      - APP_NAME=catalog-service
    networks:
      - transit
  #    scale: 3

  schedule-service:
    build:
      context: ./schedule-service
    #    container_name: transit-carts
    depends_on:
      - transit-mysql
      - eureka-server
    restart: always
    #    ports:
    #      - 8081:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=transit-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
      - SERVER_PORT=8080
      - REGISTRY_HOST=discovery
      - APP_NAME=cart-service
    networks:
      - transit
  #    scale: 3

  stops-service:
    build:
      context: ./stops-service
    #    container_name: transit-checkout
    depends_on:
      - transit-mysql
      - eureka-server
    restart: always
    #    ports:
    #      - 8082:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=transit-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
      - SERVER_PORT=8080
      - REGISTRY_HOST=discovery
      - APP_NAME=checkout-service
    networks:
      - transit
  #    scale: 3

  user-service:
    build:
      context: ./user-service
    #    container_name: transit-orders
    depends_on:
      - transit-mysql
      - eureka-server
    restart: always
    #    ports:
    #      - 8085:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=transit-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
      - SERVER_PORT=8080
      - REGISTRY_HOST=discovery
      - APP_NAME=order-service
    networks:
      - transit
  #    scale: 3

  vehicle-service:
    build:
      context: ./vehicle-service
    #    container_name: card-service
    depends_on:
      - transit-mysql
      - eureka-server
    restart: always
    #    ports:
    #      - 8083:8080
    expose:
      - 8080
    environment:
      - DATABASE_HOST=transit-mysql
      - DATABASE_NAME=ecom
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
      - SERVER_PORT=8080
      - REGISTRY_HOST=discovery
      - APP_NAME=card-service
    networks:
      - transit
  #    scale: 3

  web-server:
    build:
      context: ./web-server
    container_name: web-server
    depends_on:
      - vehicle-service
      - stops-service
      - schedule-service
      - notifications-service
      - user-service
      - cloud-gateway
      - eureka-server
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - transit

networks:
  transit:
    name: transit
